backend:
    name: github
    repo: quantal-quetzal/immobilien

locale: 'de'

media_folder: 'media'

collections:
    - name: 'immobilien' # Used in routes, e.g., /admin/collections/blog
      label: 'Immobilie' # Used in the UI
      folder: 'src/_posts/immobilien' # The path to the folder where the documents are stored
      create: true # Allow users to create new documents in this collection
      slug: '{{year}}-{{month}}-{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
      fields: # The fields for each document, usually in front matter
          - { label: 'Title', name: 'titel', widget: 'string' }
          - { label: 'Datum', name: 'datum', widget: 'datetime' }
          - {
                label: 'Kurzbeschreibung',
                name: 'kurzbeschreibung',
                widget: 'text',
            }
          - { label: 'Wohnfläche', name: 'wohnflaeche', widget: 'number' }
          - { label: 'Fotos', name: 'fotos', widget: 'string' }
